"use client"

/**
 * THIS FILE IS GENERATED by uifork.
 * Do not edit this file directly. Edit the version files instead (e.g., FloatingToolbar.v1.tsx).
 * To stop versioning this component, run: npx uifork promote FloatingToolbar <version-id>
 */
import { ForkedComponent } from "uifork"
import { VERSIONS } from "./FloatingToolbar.versions"

function FloatingToolbar(props: any) {
  return (
    <ForkedComponent
      id="FloatingToolbar"
      versions={VERSIONS}
      props={props}
    />
  )
}

export default FloatingToolbar
export { FloatingToolbar, VERSIONS }
