/**
 * THIS FILE IS GENERATED by uifork.
 * Manual edits to labels/descriptions are preserved, but structure changes may be overwritten.
 * To stop versioning this component, run: npx uifork promote FloatingToolbar <version-id>
 */
import FloatingToolbarV1 from "./FloatingToolbar.v1"

export const VERSIONS = {
  "v1": {
    render: FloatingToolbarV1,
    label: "",
  },
}
