package profile

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/nicholasgasior/margin/cli/db"
)

// FormatCodexAgentsMD generates writing rules formatted as Codex AGENTS.md instructions.
//
// Codex loads ~/.codex/AGENTS.md as global context for every session. Unlike Claude
// Code's writing_guard.py hook (which mechanically blocks violations), this is
// prompt-level instruction — Codex must choose to follow it.
//
// The generated content is wrapped in BEGIN/END markers so ExportCodex can safely
// overwrite just the managed section on re-export, leaving any existing user content intact.
func FormatCodexAgentsMD(rules []db.WritingRule, corrections []db.CorrectionRecord) string {
	var lines []string

	lines = append(lines, "<!-- BEGIN MARGIN WRITING RULES -->")
	lines = append(lines, "<!-- AUTO-GENERATED by `margin export codex`. Do not edit this section manually. -->")
	lines = append(lines, "")
	lines = append(lines, "# Writing Rules")
	lines = append(lines, "")
	lines = append(lines, "_These rules are synthesized from my reading annotations and editorial corrections in Margin._")
	lines = append(lines, "_Apply rules matching the writing type. General rules always apply._")
	lines = append(lines, "_Note: unlike Claude Code, these are instructional — not mechanically enforced._")

	// Kill words — most important, listed as explicit prohibitions
	var killWords []string
	for _, r := range rules {
		if r.Category == "kill-words" && r.Severity == "must-fix" {
			killWords = append(killWords, r.RuleText)
		}
	}
	if len(killWords) > 0 {
		lines = append(lines, "", "## Prohibited Words")
		lines = append(lines, "")
		lines = append(lines, "Do not use the following words or phrases in any writing:")
		lines = append(lines, "")
		for _, w := range killWords {
			lines = append(lines, fmt.Sprintf("- Do not use the word \"%s\"", w))
		}
	}

	// AI slop patterns
	var slopRules []db.WritingRule
	for _, r := range rules {
		if r.Category == "ai-slop" {
			slopRules = append(slopRules, r)
		}
	}
	if len(slopRules) > 0 {
		lines = append(lines, "", "## AI Slop Patterns to Avoid")
		lines = append(lines, "")
		for _, r := range slopRules {
			lines = append(lines, fmt.Sprintf("- %s", r.RuleText))
		}
	}

	// Voice calibration rules
	var voiceRules []db.WritingRule
	for _, r := range rules {
		if r.Category == "voice-calibration" {
			voiceRules = append(voiceRules, r)
		}
	}
	if len(voiceRules) > 0 {
		lines = append(lines, "", "## Voice Calibration")
		lines = append(lines, "")
		lines = append(lines, "_These are constraints derived from my writing fingerprint, not suggestions._")
		for _, r := range voiceRules {
			lines = append(lines, "")
			lines = append(lines, fmt.Sprintf("- **%s**", r.RuleText))
			if r.WhenToApply != nil {
				lines = append(lines, fmt.Sprintf("  - When: %s", *r.WhenToApply))
			}
			if r.Why != nil {
				lines = append(lines, fmt.Sprintf("  - Why: %s", *r.Why))
			}
		}
	}

	// Non-voice, non-kill, non-slop rules by writing type
	var editorialRules []db.WritingRule
	for _, r := range rules {
		if r.Category != "kill-words" && r.Category != "ai-slop" && r.Category != "voice-calibration" {
			editorialRules = append(editorialRules, r)
		}
	}
	if len(editorialRules) > 0 {
		lines = append(lines, "")
		lines = append(lines, formatRulesSection(editorialRules)...)
	}

	// Corrective examples — patterns to avoid
	var corrective []db.CorrectionRecord
	for _, c := range corrections {
		if c.Polarity != nil && *c.Polarity == "corrective" {
			corrective = append(corrective, c)
		}
	}
	if len(corrective) > 0 {
		lines = append(lines, "", "## Patterns to Avoid")
		lines = append(lines, "")
		lines = append(lines, "_These are phrases I've flagged as patterns to fix in my own writing._")
		for _, c := range corrective {
			snippet := truncateUnicode(c.OriginalText, 200)
			note := strings.Join(c.Notes, "; ")
			lines = append(lines, fmt.Sprintf("- Avoid: \"%s\" — %s", snippet, note))
		}
	}

	lines = append(lines, "", "<!-- END MARGIN WRITING RULES -->")

	return strings.Join(lines, "\n") + "\n"
}

// CodexDir returns the path to the user's ~/.codex directory.
func CodexDir() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".codex")
}

// CodexAgentsMDPath returns the path to ~/.codex/AGENTS.md.
func CodexAgentsMDPath() string {
	return filepath.Join(CodexDir(), "AGENTS.md")
}

// ExportCodex writes the writing rules into ~/.codex/AGENTS.md.
//
// If AGENTS.md already exists and contains a managed section (BEGIN/END markers),
// only that section is replaced. User content outside the markers is preserved.
// If no markers exist, the managed section is appended.
// If AGENTS.md does not exist, it is created.
//
// Does nothing if ~/.codex does not exist — Codex is not installed.
func ExportCodex(dbPath string) error {
	codexDir := CodexDir()
	if _, err := os.Stat(codexDir); os.IsNotExist(err) {
		// Codex not installed — skip silently
		return nil
	}

	d, err := db.OpenRead(dbPath)
	if err != nil {
		return err
	}
	defer d.Close()

	rules, err := db.GetWritingRules(d, nil)
	if err != nil {
		return err
	}

	corrections, err := db.GetAllCorrectionsForProfile(d)
	if err != nil {
		return err
	}

	managed := FormatCodexAgentsMD(rules, corrections)
	agentsPath := CodexAgentsMDPath()

	// Merge into existing file if present
	existing, readErr := os.ReadFile(agentsPath)
	if readErr == nil {
		merged := mergeCodexAgentsMD(string(existing), managed)
		return os.WriteFile(agentsPath, []byte(merged), 0644)
	}

	// New file
	if err := os.MkdirAll(codexDir, 0755); err != nil {
		return fmt.Errorf("failed to create ~/.codex: %w", err)
	}
	return os.WriteFile(agentsPath, []byte(managed), 0644)
}

const beginMarker = "<!-- BEGIN MARGIN WRITING RULES -->"
const endMarker = "<!-- END MARGIN WRITING RULES -->"

// mergeCodexAgentsMD replaces the managed section in existing content with newManaged.
// If no markers are found, newManaged is appended to existing content.
func mergeCodexAgentsMD(existing, newManaged string) string {
	beginIdx := strings.Index(existing, beginMarker)
	endIdx := strings.Index(existing, endMarker)

	if beginIdx == -1 || endIdx == -1 || endIdx < beginIdx {
		// No existing managed section — append
		if strings.TrimSpace(existing) == "" {
			return newManaged
		}
		return strings.TrimRight(existing, "\n") + "\n\n" + newManaged
	}

	// Replace the managed section (inclusive of end marker + trailing newline)
	endOfSection := endIdx + len(endMarker)
	if endOfSection < len(existing) && existing[endOfSection] == '\n' {
		endOfSection++
	}

	before := existing[:beginIdx]
	after := existing[endOfSection:]

	result := strings.TrimRight(before, "\n")
	if result != "" {
		result += "\n\n"
	}
	result += newManaged
	if strings.TrimSpace(after) != "" {
		result += "\n" + strings.TrimLeft(after, "\n")
	}
	return result
}
