package profile

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/nicholasgasior/margin/cli/db"
)

// FormatCodexAgentsMD generates a bounded pointer to the full writing profile.
// Rule bodies stay in ~/.margin/writing-rules.md and are loaded for writing tasks.
func FormatCodexAgentsMD(_ []db.WritingRule, _ []db.CorrectionRecord) string {
	return beginMarker + "\n" +
		"<!-- AUTO-GENERATED by `margin export codex`. Do not edit this section manually. -->\n\n" +
		"# Writing Rules\n\n" +
		"For drafting, editing, or reviewing audience-facing prose, read ~/.margin/writing-rules.md before writing. When writing as Sam, also use the my-voice skill and its matching channel reference. Do not load the full profile for code, routine operations, or brief status replies.\n\n" +
		"Apply the current user request and source facts first, then channel-specific guidance, then general style. For casual texts and DMs, fragments and omitted final periods may match the relationship. For professional prose, use complete sentences and terminal punctuation. Do not transfer casual punctuation or intimacy into professional correspondence.\n\n" +
		"Preserve facts, direct quotations, useful uncertainty, and approval boundaries. Examples illustrate style; they do not authorize sends or supply facts for a new artifact. Editorial instructions stored under kill-words remain instructions, not literal banned phrases. Resolve conflicting examples using their audience, channel, and the latest explicit correction.\n\n" +
		"Keep routine replies concise and actionable. Full writing rules are guidance, not proof of compliance; check the finished artifact against its reader and purpose.\n\n" +
		endMarker + "\n"
}

// CodexDir returns the path to the user's ~/.codex directory.
func CodexDir() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".codex")
}

// CodexAgentsMDPath returns the path to ~/.codex/AGENTS.md.
func CodexAgentsMDPath() string {
	return filepath.Join(CodexDir(), "AGENTS.md")
}

// ExportCodex writes the full profile and a bounded router in ~/.codex/AGENTS.md.
//
// If AGENTS.md already exists and contains a managed section (BEGIN/END markers),
// only that section is replaced. User content outside the markers is preserved.
// If no markers exist, the managed section is appended.
// If AGENTS.md does not exist, it is created.
//
// Does nothing if ~/.codex does not exist — Codex is not installed.
func ExportCodex(dbPath string) error {
	codexDir := CodexDir()
	if _, err := os.Stat(codexDir); os.IsNotExist(err) {
		// Codex not installed — skip silently
		return nil
	}

	d, err := db.OpenRead(dbPath)
	if err != nil {
		return err
	}
	defer d.Close()

	rules, err := db.GetWritingRules(d, nil)
	if err != nil {
		return err
	}
	accepted := make([]db.WritingRule, 0, len(rules))
	for _, rule := range rules {
		if !rule.IsUnreviewedCandidate() {
			accepted = append(accepted, rule)
		}
	}

	corrections, err := db.GetAllCorrectionsForProfile(d)
	if err != nil {
		return err
	}

	// Write the referenced artifact before installing its router.
	profileDir := filepath.Join(filepath.Dir(codexDir), ".margin")
	if err := os.MkdirAll(profileDir, 0755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(profileDir, "writing-rules.md"), []byte(FormatProfileMarkdown(accepted, corrections)), 0644); err != nil {
		return err
	}
	return writeCodexAgentsMD(FormatCodexAgentsMD(accepted, corrections))
}

// Shared by direct Codex export and the universal profile export.
func writeCodexAgentsMD(managed string) error {
	agentsPath := CodexAgentsMDPath()

	// Merge into existing file if present
	existing, readErr := os.ReadFile(agentsPath)
	if readErr == nil {
		merged := mergeCodexAgentsMD(string(existing), managed)
		return os.WriteFile(agentsPath, []byte(merged), 0644)
	}
	if !os.IsNotExist(readErr) {
		return fmt.Errorf("failed to read %s: %w", agentsPath, readErr)
	}

	// New file
	if err := os.MkdirAll(CodexDir(), 0755); err != nil {
		return fmt.Errorf("failed to create ~/.codex: %w", err)
	}
	return os.WriteFile(agentsPath, []byte(managed), 0644)
}

const beginMarker = "<!-- BEGIN MARGIN WRITING RULES -->"
const endMarker = "<!-- END MARGIN WRITING RULES -->"

// mergeCodexAgentsMD replaces the managed section in existing content with newManaged.
// If no markers are found, newManaged is appended to existing content.
func mergeCodexAgentsMD(existing, newManaged string) string {
	beginIdx := strings.Index(existing, beginMarker)
	endIdx := strings.Index(existing, endMarker)

	if beginIdx == -1 || endIdx == -1 || endIdx < beginIdx {
		// No existing managed section — append
		if strings.TrimSpace(existing) == "" {
			return newManaged
		}
		return strings.TrimRight(existing, "\n") + "\n\n" + newManaged
	}

	// Replace the managed section (inclusive of end marker + trailing newline)
	endOfSection := endIdx + len(endMarker)
	if endOfSection < len(existing) && existing[endOfSection] == '\n' {
		endOfSection++
	}

	before := existing[:beginIdx]
	after := existing[endOfSection:]

	result := strings.TrimRight(before, "\n")
	if result != "" {
		result += "\n\n"
	}
	result += newManaged
	if strings.TrimSpace(after) != "" {
		result += "\n" + strings.TrimLeft(after, "\n")
	}
	return result
}
