package profile

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/nicholasgasior/margin/cli/db"
)

// truncateUnicode truncates to max code points (not bytes).
func truncateUnicode(text string, max int) string {
	count := utf8.RuneCountInString(text)
	if count <= max {
		return text
	}
	runes := []rune(text)
	return string(runes[:max]) + "…"
}

func categoryLabel(cat string) string {
	words := strings.Split(strings.ReplaceAll(cat, "-", " "), " ")
	for i, w := range words {
		if len(w) > 0 {
			words[i] = strings.ToUpper(w[:1]) + w[1:]
		}
	}
	return strings.Join(words, " ")
}

// FormatRulesMarkdown generates rules-only markdown.
func FormatRulesMarkdown(rules []db.WritingRule) string {
	var lines []string
	lines = append(lines, "# Writing Rules", "")
	lines = append(lines, "_For AI agents: apply rules matching the writing type. General rules always apply._")
	lines = append(lines, formatRulesSection(rules)...)
	lines = append(lines, "")
	return strings.Join(lines, "\n")
}

// FormatProfileMarkdown generates the full writing profile.
func FormatProfileMarkdown(rules []db.WritingRule, corrections []db.CorrectionRecord) string {
	var lines []string
	lines = append(lines, "# Writing Profile", "")
	lines = append(lines, "_Generated by Margin. Voice calibration + corrections + writing rules in one file._")
	lines = append(lines, "_For AI agents: apply rules matching the writing type. General rules always apply._")

	// Voice calibration
	var voiceRules []db.WritingRule
	for _, r := range rules {
		if r.Category == "voice-calibration" {
			voiceRules = append(voiceRules, r)
		}
	}
	if len(voiceRules) > 0 {
		lines = append(lines, "", "---", "", "## Voice Calibration", "")
		lines = append(lines, "_Statistical voice fingerprint. These are constraints, not suggestions._")
		for _, rule := range voiceRules {
			lines = append(lines, "", fmt.Sprintf("- **%s**", rule.RuleText))
			if rule.WhenToApply != nil {
				lines = append(lines, fmt.Sprintf("  - When: %s", *rule.WhenToApply))
			}
			if rule.Why != nil {
				lines = append(lines, fmt.Sprintf("  - Why: %s", *rule.Why))
			}
		}
	}

	// Corrections by polarity
	var positive, corrective, unclassified []db.CorrectionRecord
	for _, c := range corrections {
		switch {
		case c.Polarity != nil && *c.Polarity == "positive":
			positive = append(positive, c)
		case c.Polarity != nil && *c.Polarity == "corrective":
			corrective = append(corrective, c)
		default:
			unclassified = append(unclassified, c)
		}
	}

	if len(positive) > 0 {
		lines = append(lines, "", "---", "", "## Writing Samples", "")
		lines = append(lines, "_Patterns to emulate — do more of this._")
		for _, c := range positive {
			snippet := truncateUnicode(c.OriginalText, 200)
			lines = append(lines, "", fmt.Sprintf("> %s", strings.ReplaceAll(snippet, "\n", "\n> ")))
			if len(c.Notes) > 0 {
				lines = append(lines, fmt.Sprintf("— %s", strings.Join(c.Notes, "; ")))
			}
		}
	}

	if len(corrective) > 0 {
		lines = append(lines, "", "---", "", "## Corrections", "")
		lines = append(lines, "_Patterns to avoid — don't do this._")
		for _, c := range corrective {
			snippet := truncateUnicode(c.OriginalText, 200)
			lines = append(lines, "", fmt.Sprintf("- **%s** → %s", snippet, strings.Join(c.Notes, "; ")))
		}
	}

	if len(unclassified) > 0 {
		lines = append(lines, "", "---", "", "## Unclassified", "")
		lines = append(lines, "_These annotations haven't been tagged as positive or corrective yet._")
		for _, c := range unclassified {
			snippet := truncateUnicode(c.OriginalText, 120)
			note := "flagged"
			if len(c.Notes) > 0 {
				note = strings.Join(c.Notes, "; ")
			}
			lines = append(lines, "", fmt.Sprintf("- %s → %s", snippet, note))
		}
	}

	// Non-voice rules
	var nonVoiceRules []db.WritingRule
	for _, r := range rules {
		if r.Category != "voice-calibration" {
			nonVoiceRules = append(nonVoiceRules, r)
		}
	}
	if len(nonVoiceRules) > 0 {
		lines = append(lines, "", "---", "", "# Writing Rules", "")
		lines = append(lines, "_Synthesized from corrections and editorial preferences._")
		lines = append(lines, formatRulesSection(nonVoiceRules)...)
	}

	lines = append(lines, "")
	return strings.Join(lines, "\n")
}

func formatRulesSection(rules []db.WritingRule) []string {
	var lines []string

	groups := make(map[string][]db.WritingRule)
	for _, r := range rules {
		groups[r.WritingType] = append(groups[r.WritingType], r)
	}

	keys := make([]string, 0, len(groups))
	for k := range groups {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		if keys[i] == "general" {
			return true
		}
		if keys[j] == "general" {
			return false
		}
		return keys[i] < keys[j]
	})

	for _, wt := range keys {
		groupRules := groups[wt]
		label := db.TypeLabels[wt]
		if label == "" {
			label = wt
		}
		lines = append(lines, "", fmt.Sprintf("## %s", label))

		catGroups := make(map[string][]db.WritingRule)
		var catOrder []string
		for _, r := range groupRules {
			if _, seen := catGroups[r.Category]; !seen {
				catOrder = append(catOrder, r.Category)
			}
			catGroups[r.Category] = append(catGroups[r.Category], r)
		}

		for _, cat := range catOrder {
			catRules := catGroups[cat]
			lines = append(lines, "", fmt.Sprintf("### %s", categoryLabel(cat)))

			for _, rule := range catRules {
				lines = append(lines, "", fmt.Sprintf("**Rule: %s** [%s]", rule.RuleText, rule.Severity))
				if rule.WhenToApply != nil {
					lines = append(lines, fmt.Sprintf("- When to apply: %s", *rule.WhenToApply))
				}
				if rule.Why != nil {
					lines = append(lines, fmt.Sprintf("- Why: %s", *rule.Why))
				}
				lines = append(lines, fmt.Sprintf("- Signal: seen %d time(s)", rule.SignalCount))
				if rule.ExampleBefore != nil || rule.ExampleAfter != nil {
					lines = append(lines, "- Before -> After:")
					if rule.ExampleBefore != nil {
						lines = append(lines, fmt.Sprintf(`  - Before: "%s"`, *rule.ExampleBefore))
					}
					if rule.ExampleAfter != nil {
						lines = append(lines, fmt.Sprintf(`  - After: "%s"`, *rule.ExampleAfter))
					}
				}
				if rule.Notes != nil {
					lines = append(lines, fmt.Sprintf("- Notes: %s", *rule.Notes))
				}
			}
		}
	}

	return lines
}

// guardFamily extracts the soft-pattern family tag from a rule's notes
// ("slop-family:copula-avoidance"), falling back to the rule's category.
func guardFamily(r db.WritingRule) string {
	if r.Notes != nil {
		for _, line := range strings.Split(*r.Notes, "\n") {
			if strings.HasPrefix(line, "slop-family:") {
				return strings.TrimSpace(strings.TrimPrefix(line, "slop-family:"))
			}
		}
	}
	return r.Category
}

// GenerateWritingGuardPy generates the Python hook script.
// This is the canonical generator — Rust and MCP delegate to the CLI.
//
// v2 contract: a rule contributes a mechanical pattern ONLY via its
// detection_pattern column (a curated regex). example_before is
// illustrative — the v1 behavior of executing it as a regex produced
// verbatim past sentences as "patterns" that never matched future prose.
//
// Enforcement model:
//   - HARD (single hit asks on published docs): kill words, prohibition
//     rules with a detection_pattern, heading patterns, em-dash budget.
//   - SOFT (cluster-scored): other detection_pattern rules, grouped into
//     families; a published doc asks only when >= 2 distinct families
//     co-occur. A single family is advisory. Isolated tells are normal
//     in human prose — co-occurrence is the AI signal.
func GenerateWritingGuardPy(rules []db.WritingRule) string {
	var killWords []string
	var hardPatterns [][2]string
	var softPatterns [][3]string
	var headingPatterns [][2]string

	for _, r := range rules {
		if r.Severity == "must-fix" && r.Category == "kill-words" {
			killWords = append(killWords, r.RuleText)
		}
		if r.Category == "heading-patterns" && r.Severity == "must-fix" && r.ExampleBefore != nil {
			headingPatterns = append(headingPatterns, [2]string{*r.ExampleBefore, r.RuleText})
		}
		if r.DetectionPattern != nil && *r.DetectionPattern != "" {
			if r.Category == "prohibition" {
				hardPatterns = append(hardPatterns, [2]string{*r.DetectionPattern, r.RuleText})
			} else {
				softPatterns = append(softPatterns, [3]string{*r.DetectionPattern, r.RuleText, guardFamily(r)})
			}
		}
	}

	killWordsJSON, _ := json.Marshal(killWords)
	hardPatternsJSON, _ := json.Marshal(hardPatterns)
	softPatternsJSON, _ := json.Marshal(softPatterns)
	headingPatternsJSON, _ := json.Marshal(headingPatterns)

	for _, blob := range [][]byte{killWordsJSON, hardPatternsJSON, softPatternsJSON, headingPatternsJSON} {
		if strings.Contains(string(blob), `"""`) {
			return `#!/usr/bin/env python3
# ERROR: A writing rule contains a triple-quote sequence that cannot be safely
# embedded. Remove the offending rule text and re-export.
import sys; print('writing_guard: triple-quote injection blocked — skipping guard', file=sys.stderr); sys.exit(1)
`
		}
	}

	return fmt.Sprintf(`#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Writing guard hook — AUTO-GENERATED by Margin's export_writing_rules command.
Do not edit manually. Changes will be overwritten.

The encoding cookie above is required: the rule data below embeds non-ASCII
bytes (em dashes are kill-word targets), and some interpreters — notably Apple's
system python3 under a C/empty locale — default source decoding to ASCII and
would raise a SyntaxError without it.

Kill words and slop patterns are loaded from JSON data blobs for safety.
Source of truth: ~/.margin/margin.db (writing_rules table)
"""
import json, sys, re

# Only check prose file extensions
PROSE_EXTENSIONS = {".md", ".mdx", ".txt", ".html", ".htm"}

# Paths where writing is externally published — full enforcement (blocks the write).
# Anything NOT under one of these markers is treated as an internal doc: violations
# are surfaced as advisory-only (printed, never blocking). The guard matters most for
# what ships to other people; internal drafts, plans, and notes should not be gated.
PUBLISHED_PATH_MARKERS = ["/Projects/personal-site/", "/personal-site/", "/substack/", "/published/"]

def is_published(path):
    p = (path or "").replace("\\", "/")
    return any(marker in p for marker in PUBLISHED_PATH_MARKERS)

# Kill words — loaded from JSON for codegen safety.
KILL_WORDS = json.loads(r"""%s""")

# Hard patterns — [regex, explanation]. A single hit is a violation
# (prohibition-backed rules with curated detection patterns).
HARD_PATTERNS = json.loads(r"""%s""")

# Soft patterns — [regex, explanation, family]. Cluster-scored: a published
# doc is flagged only when >= 2 distinct families co-occur. Isolated tells
# are normal in human prose; co-occurrence is the AI signal.
SOFT_PATTERNS = json.loads(r"""%s""")

# Heading patterns — [regex, explanation] applied per heading line
HEADING_PATTERNS = json.loads(r"""%s""")

def compiled(patterns):
    """Compile pattern rows, skipping any invalid regex (fail-open per pattern)."""
    out = []
    for row in patterns:
        try:
            out.append((re.compile(row[0]), *row[1:]))
        except re.error:
            continue
    return out

def get_extension(path):
    if not path:
        return ""
    dot = path.rfind(".")
    return path[dot:].lower() if dot != -1 else ""

def main():
    try:
        data = json.load(sys.stdin)
        tool = data.get("tool_name", "")
        inp = data.get("tool_input") or {}

        # Determine file path and text to check
        path = ""
        text = ""
        if tool == "Write":
            path = inp.get("file_path", "")
            text = inp.get("content", "")
        elif tool == "Edit":
            path = inp.get("file_path", "")
            text = inp.get("new_string", "")

        if not text or get_extension(path) not in PROSE_EXTENSIONS:
            sys.exit(0)

        hard = []            # single hit = violation
        soft_by_family = {}  # family -> [explanations]; blocks only on co-occurrence

        # Kill words — hard
        lower = text.lower()
        for word in KILL_WORDS:
            if word in lower:
                hard.append(f'Kill word: "{word}"')

        # Prohibition-backed patterns — hard
        for rx, explanation in compiled(HARD_PATTERNS):
            if rx.search(text):
                hard.append(explanation)

        # Heading patterns — hard. Section headings only (## and deeper):
        # the H1 is the document's title, which these rules don't govern.
        if HEADING_PATTERNS:
            compiled_headings = compiled(HEADING_PATTERNS)
            for line in text.splitlines():
                stripped = line.strip()
                if not stripped.startswith('##'):
                    continue
                heading_text = stripped.lstrip('#').strip()
                if not heading_text:
                    continue
                for rx, explanation in compiled_headings:
                    if rx.search(heading_text):
                        hard.append(f'{explanation}: "{stripped}"')
                        break

        # Soft patterns — cluster-scored by family
        for rx, explanation, family in compiled(SOFT_PATTERNS):
            m = rx.search(text)
            if m:
                soft_by_family.setdefault(family, []).append(
                    f'{explanation} (matched: "{m.group(0)[:60]}")')

        published = is_published(path)

        # Em dash budget applies only to published docs (limit 1-2 per document).
        if published:
            em = text.count("—")
            if em > 2:
                hard.append(f'Em dash overuse: {em} em dashes; limit to 1-2 per published document.')

        soft_families = sorted(soft_by_family)
        cluster = len(soft_families) >= 2
        blocking = hard + ([v for f in soft_families for v in soft_by_family[f]] if cluster else [])
        advisory_only = [] if cluster else [v for f in soft_families for v in soft_by_family[f]]

        if blocking or advisory_only:
            if not published or not blocking:
                # Internal doc, or a single soft family on a published doc:
                # advisory only, never block the write.
                note = "WRITING GUARD (advisory — not blocking):\n"
                shown = (blocking + advisory_only)[:8]
                for v in shown:
                    note += f"  - {v}\n"
                remaining = len(blocking) + len(advisory_only) - len(shown)
                if remaining > 0:
                    note += f"  ... and {remaining} more\n"
                print(note, file=sys.stderr)
                sys.exit(0)

            msg = "WRITING GUARD: Writing rule violations detected:\n"
            for v in blocking:
                msg += f"  - {v}\n"
            if cluster:
                msg += f"AI-tell cluster: {len(soft_families)} pattern families co-occur ({', '.join(soft_families)}).\n"
            msg += "Fix violations. See ~/.margin/writing-rules.md for rules."

            print(json.dumps({
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": "ask",
                    "permissionDecisionReason": msg
                }
            }))

    except Exception as e:
        # Fail-open: never block writes due to hook errors
        print(f"Writing guard encountered an error (fail-open): {e}", file=sys.stderr)

    sys.exit(0)

if __name__ == "__main__":
    main()
`, string(killWordsJSON), string(hardPatternsJSON), string(softPatternsJSON), string(headingPatternsJSON))
}

// ExportProfile writes the unified writing profile and agent-specific artifacts.
//
// target="" (default): writes ~/.margin/writing-rules.md and
// ~/.claude/hooks/writing_guard.py. Also updates ~/.codex/AGENTS.md if
// ~/.codex exists (opt-in by directory presence). Errors updating Codex are
// non-fatal — they don't break the Claude pipeline if Codex isn't set up.
//
// target="codex": writes ~/.margin/writing-rules.md and ~/.codex/AGENTS.md.
// Skips writing_guard.py — Codex uses prompt-level instructions instead of a hook.
func ExportProfile(dbPath string, target string) error {
	d, err := db.OpenRead(dbPath)
	if err != nil {
		return err
	}
	defer d.Close()

	rules, err := db.GetWritingRules(d, nil)
	if err != nil {
		return err
	}

	corrections, err := db.GetAllCorrectionsForProfile(d)
	if err != nil {
		return err
	}

	home, _ := os.UserHomeDir()

	// Always write writing-rules.md — the universal, LLM-agnostic artifact.
	profileMD := FormatProfileMarkdown(rules, corrections)
	rulesPath := filepath.Join(home, ".margin", "writing-rules.md")
	if err := os.WriteFile(rulesPath, []byte(profileMD), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", rulesPath, err)
	}

	if target == "codex" {
		// Codex target: update AGENTS.md instead of writing the Claude hook.
		return ExportCodex(dbPath)
	}

	// Default (Claude) target: write writing_guard.py.
	guardPy := GenerateWritingGuardPy(rules)
	hooksDir := filepath.Join(home, ".claude", "hooks")
	os.MkdirAll(hooksDir, 0755)
	guardPath := filepath.Join(hooksDir, "writing_guard.py")
	if err := os.WriteFile(guardPath, []byte(guardPy), 0755); err != nil {
		return fmt.Errorf("failed to write %s: %w", guardPath, err)
	}

	// Also update ~/.codex/AGENTS.md if Codex CLI is installed (opt-in by directory presence).
	// Errors are non-fatal — don't break the Claude pipeline if Codex isn't set up.
	if _, statErr := os.Stat(CodexDir()); statErr == nil {
		managed := FormatCodexAgentsMD(rules, corrections)
		agentsPath := CodexAgentsMDPath()
		existing, readErr := os.ReadFile(agentsPath)
		var content string
		if readErr == nil {
			content = mergeCodexAgentsMD(string(existing), managed)
		} else {
			content = managed
		}
		_ = os.WriteFile(agentsPath, []byte(content), 0644)
	}

	return nil
}
