package profile

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/nicholasgasior/margin/cli/db"
)

// isSafeAutoCorrection reports whether an auto-synthesized correction's
// example_before is specific enough to be used as a substring trigger in the
// writing guard. Substring matching on short or single-word strings produces
// catastrophic false positives — e.g. " ", "doing", "landscape", or a bare
// em dash match essentially every document. A real correction target is a
// distinctive multi-word phrase. Require: 12–80 runes, contains whitespace
// (multi-word), and contains at least one letter.
// hasLetter reports whether s contains at least one Unicode letter.
func hasLetter(s string) bool {
	for _, r := range s {
		if unicode.IsLetter(r) {
			return true
		}
	}
	return false
}

func isSafeAutoCorrection(s string) bool {
	trimmed := strings.TrimSpace(s)
	n := utf8.RuneCountInString(trimmed)
	if n < 12 || n > 80 {
		return false
	}
	if !strings.ContainsAny(trimmed, " \t\n") {
		return false
	}
	return hasLetter(trimmed)
}

// truncateUnicode truncates to max code points (not bytes).
func truncateUnicode(text string, max int) string {
	count := utf8.RuneCountInString(text)
	if count <= max {
		return text
	}
	runes := []rune(text)
	return string(runes[:max]) + "…"
}

func categoryLabel(cat string) string {
	words := strings.Split(strings.ReplaceAll(cat, "-", " "), " ")
	for i, w := range words {
		if len(w) > 0 {
			words[i] = strings.ToUpper(w[:1]) + w[1:]
		}
	}
	return strings.Join(words, " ")
}

// FormatRulesMarkdown generates rules-only markdown.
func FormatRulesMarkdown(rules []db.WritingRule) string {
	var lines []string
	lines = append(lines, "# Writing Rules", "")
	lines = append(lines, "_For AI agents: apply rules matching the writing type. General rules always apply._")
	lines = append(lines, formatRulesSection(rules)...)
	lines = append(lines, "")
	return strings.Join(lines, "\n")
}

// FormatProfileMarkdown generates the full writing profile.
func FormatProfileMarkdown(rules []db.WritingRule, corrections []db.CorrectionRecord) string {
	var lines []string
	lines = append(lines, "# Writing Profile", "")
	lines = append(lines, "_Generated by Margin. Voice calibration + corrections + writing rules in one file._")
	lines = append(lines, "_For AI agents: apply rules matching the writing type. General rules always apply._")

	// Voice calibration
	var voiceRules []db.WritingRule
	for _, r := range rules {
		if r.Category == "voice-calibration" {
			voiceRules = append(voiceRules, r)
		}
	}
	if len(voiceRules) > 0 {
		lines = append(lines, "", "---", "", "## Voice Calibration", "")
		lines = append(lines, "_Statistical voice fingerprint. These are constraints, not suggestions._")
		for _, rule := range voiceRules {
			lines = append(lines, "", fmt.Sprintf("- **%s**", rule.RuleText))
			if rule.WhenToApply != nil {
				lines = append(lines, fmt.Sprintf("  - When: %s", *rule.WhenToApply))
			}
			if rule.Why != nil {
				lines = append(lines, fmt.Sprintf("  - Why: %s", *rule.Why))
			}
		}
	}

	// Corrections by polarity
	var positive, corrective, unclassified []db.CorrectionRecord
	for _, c := range corrections {
		switch {
		case c.Polarity != nil && *c.Polarity == "positive":
			positive = append(positive, c)
		case c.Polarity != nil && *c.Polarity == "corrective":
			corrective = append(corrective, c)
		default:
			unclassified = append(unclassified, c)
		}
	}

	if len(positive) > 0 {
		lines = append(lines, "", "---", "", "## Writing Samples", "")
		lines = append(lines, "_Patterns to emulate — do more of this._")
		for _, c := range positive {
			snippet := truncateUnicode(c.OriginalText, 200)
			lines = append(lines, "", fmt.Sprintf("> %s", strings.ReplaceAll(snippet, "\n", "\n> ")))
			if len(c.Notes) > 0 {
				lines = append(lines, fmt.Sprintf("— %s", strings.Join(c.Notes, "; ")))
			}
		}
	}

	if len(corrective) > 0 {
		lines = append(lines, "", "---", "", "## Corrections", "")
		lines = append(lines, "_Patterns to avoid — don't do this._")
		for _, c := range corrective {
			snippet := truncateUnicode(c.OriginalText, 200)
			lines = append(lines, "", fmt.Sprintf("- **%s** → %s", snippet, strings.Join(c.Notes, "; ")))
		}
	}

	if len(unclassified) > 0 {
		lines = append(lines, "", "---", "", "## Unclassified", "")
		lines = append(lines, "_These annotations haven't been tagged as positive or corrective yet._")
		for _, c := range unclassified {
			snippet := truncateUnicode(c.OriginalText, 120)
			note := "flagged"
			if len(c.Notes) > 0 {
				note = strings.Join(c.Notes, "; ")
			}
			lines = append(lines, "", fmt.Sprintf("- %s → %s", snippet, note))
		}
	}

	// Non-voice rules
	var nonVoiceRules []db.WritingRule
	for _, r := range rules {
		if r.Category != "voice-calibration" {
			nonVoiceRules = append(nonVoiceRules, r)
		}
	}
	if len(nonVoiceRules) > 0 {
		lines = append(lines, "", "---", "", "# Writing Rules", "")
		lines = append(lines, "_Synthesized from corrections and editorial preferences._")
		lines = append(lines, formatRulesSection(nonVoiceRules)...)
	}

	lines = append(lines, "")
	return strings.Join(lines, "\n")
}

func formatRulesSection(rules []db.WritingRule) []string {
	var lines []string

	groups := make(map[string][]db.WritingRule)
	for _, r := range rules {
		groups[r.WritingType] = append(groups[r.WritingType], r)
	}

	keys := make([]string, 0, len(groups))
	for k := range groups {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		if keys[i] == "general" {
			return true
		}
		if keys[j] == "general" {
			return false
		}
		return keys[i] < keys[j]
	})

	for _, wt := range keys {
		groupRules := groups[wt]
		label := db.TypeLabels[wt]
		if label == "" {
			label = wt
		}
		lines = append(lines, "", fmt.Sprintf("## %s", label))

		catGroups := make(map[string][]db.WritingRule)
		var catOrder []string
		for _, r := range groupRules {
			if _, seen := catGroups[r.Category]; !seen {
				catOrder = append(catOrder, r.Category)
			}
			catGroups[r.Category] = append(catGroups[r.Category], r)
		}

		for _, cat := range catOrder {
			catRules := catGroups[cat]
			lines = append(lines, "", fmt.Sprintf("### %s", categoryLabel(cat)))

			for _, rule := range catRules {
				lines = append(lines, "", fmt.Sprintf("**Rule: %s** [%s]", rule.RuleText, rule.Severity))
				if rule.WhenToApply != nil {
					lines = append(lines, fmt.Sprintf("- When to apply: %s", *rule.WhenToApply))
				}
				if rule.Why != nil {
					lines = append(lines, fmt.Sprintf("- Why: %s", *rule.Why))
				}
				lines = append(lines, fmt.Sprintf("- Signal: seen %d time(s)", rule.SignalCount))
				if rule.ExampleBefore != nil || rule.ExampleAfter != nil {
					lines = append(lines, "- Before -> After:")
					if rule.ExampleBefore != nil {
						lines = append(lines, fmt.Sprintf(`  - Before: "%s"`, *rule.ExampleBefore))
					}
					if rule.ExampleAfter != nil {
						lines = append(lines, fmt.Sprintf(`  - After: "%s"`, *rule.ExampleAfter))
					}
				}
				if rule.Notes != nil {
					lines = append(lines, fmt.Sprintf("- Notes: %s", *rule.Notes))
				}
			}
		}
	}

	return lines
}

// GenerateWritingGuardPy generates the Python hook script.
// This is the canonical generator — Rust and MCP delegate to the CLI.
func GenerateWritingGuardPy(rules []db.WritingRule) string {
	var killWords []string
	var slopPatterns [][2]string
	var headingPatterns [][2]string
	var autoCorrections [][2]string

	for _, r := range rules {
		if r.Severity == "must-fix" && r.Category == "kill-words" {
			killWords = append(killWords, r.RuleText)
		}
		if r.Category == "ai-slop" && r.ExampleBefore != nil && hasLetter(*r.ExampleBefore) {
			// A slop "pattern" with no letters (e.g. a bare "—") is a miscategorized
			// rule that regex-matches every document — drop it. Real slop patterns
			// are words or example sentences.
			slopPatterns = append(slopPatterns, [2]string{*r.ExampleBefore, r.RuleText})
		}
		if r.Category == "heading-patterns" && r.Severity == "must-fix" && r.ExampleBefore != nil {
			headingPatterns = append(headingPatterns, [2]string{*r.ExampleBefore, r.RuleText})
		}
		if r.Category == "auto-synthesized" && r.Severity == "must-fix" && r.ExampleBefore != nil {
			if isSafeAutoCorrection(*r.ExampleBefore) {
				autoCorrections = append(autoCorrections, [2]string{*r.ExampleBefore, r.RuleText})
			}
		}
	}

	killWordsJSON, _ := json.Marshal(killWords)
	slopPatternsJSON, _ := json.Marshal(slopPatterns)
	headingPatternsJSON, _ := json.Marshal(headingPatterns)
	autoCorrectionsJSON, _ := json.Marshal(autoCorrections)

	for _, blob := range [][]byte{killWordsJSON, slopPatternsJSON, headingPatternsJSON, autoCorrectionsJSON} {
		if strings.Contains(string(blob), `"""`) {
			return `#!/usr/bin/env python3
# ERROR: A writing rule contains a triple-quote sequence that cannot be safely
# embedded. Remove the offending rule text and re-export.
import sys; print('writing_guard: triple-quote injection blocked — skipping guard', file=sys.stderr); sys.exit(1)
`
		}
	}

	return fmt.Sprintf(`#!/usr/bin/env python3
"""
Writing guard hook — AUTO-GENERATED by Margin's export_writing_rules command.
Do not edit manually. Changes will be overwritten.

Kill words and slop patterns are loaded from JSON data blobs for safety.
Source of truth: ~/.margin/margin.db (writing_rules table)
"""
import json, sys, re

# Only check prose file extensions
PROSE_EXTENSIONS = {".md", ".mdx", ".txt", ".html", ".htm"}

# Paths where writing is externally published — full enforcement (blocks the write).
# Anything NOT under one of these markers is treated as an internal doc: violations
# are surfaced as advisory-only (printed, never blocking). The guard matters most for
# what ships to other people; internal drafts, plans, and notes should not be gated.
PUBLISHED_PATH_MARKERS = ["/Projects/personal-site/", "/personal-site/", "/substack/", "/published/"]

def is_published(path):
    p = (path or "").replace("\\", "/")
    return any(marker in p for marker in PUBLISHED_PATH_MARKERS)

# Kill words — loaded from JSON for codegen safety.
KILL_WORDS = json.loads(r"""%s""")

# AI-slop sentence patterns — [pattern, explanation]
SLOP_PATTERNS = json.loads(r"""%s""")

# Heading patterns — [regex, explanation] applied per heading line
HEADING_PATTERNS = json.loads(r"""%s""")

# Auto-synthesized corrections — [original_text, explanation] substring match
AUTO_CORRECTIONS = json.loads(r"""%s""")

def get_extension(path):
    if not path:
        return ""
    dot = path.rfind(".")
    return path[dot:].lower() if dot != -1 else ""

def main():
    try:
        data = json.load(sys.stdin)
        tool = data.get("tool_name", "")
        inp = data.get("tool_input") or {}

        # Determine file path and text to check
        path = ""
        text = ""
        if tool == "Write":
            path = inp.get("file_path", "")
            text = inp.get("content", "")
        elif tool == "Edit":
            path = inp.get("file_path", "")
            text = inp.get("new_string", "")

        if not text or get_extension(path) not in PROSE_EXTENSIONS:
            sys.exit(0)

        violations = []

        # Check kill words
        lower = text.lower()
        for word in KILL_WORDS:
            if word in lower:
                violations.append(f'Kill word: "{word}"')

        # Check slop patterns
        for pattern, explanation in SLOP_PATTERNS:
            if re.search(pattern, text):
                violations.append(explanation)

        # Check heading patterns
        if HEADING_PATTERNS:
            for line in text.splitlines():
                stripped = line.strip()
                if not stripped.startswith('#'):
                    continue
                heading_text = stripped.lstrip('#').strip()
                if not heading_text:
                    continue
                for pattern, explanation in HEADING_PATTERNS:
                    if re.search(pattern, heading_text):
                        violations.append(f'{explanation}: "{stripped}"')
                        break

        # Check auto-synthesized corrections (substring match)
        for original_text, explanation in AUTO_CORRECTIONS:
            if original_text.lower() in lower:
                violations.append(f'Auto-correction: "{original_text}" — {explanation}')

        published = is_published(path)

        # Em dash budget applies only to published docs (limit 1-2 per document).
        if published:
            em = text.count("—")
            if em > 2:
                violations.append(f'Em dash overuse: {em} em dashes; limit to 1-2 per published document.')

        if violations:
            if not published:
                # Internal doc: advisory only, never block the write.
                note = "WRITING GUARD (advisory — internal doc, not blocking):\n"
                for v in violations[:8]:
                    note += f"  - {v}\n"
                if len(violations) > 8:
                    note += f"  ... and {len(violations) - 8} more\n"
                print(note, file=sys.stderr)
                sys.exit(0)

            msg = "WRITING GUARD: Writing rule violations detected:\n"
            for v in violations:
                msg += f"  - {v}\n"
            msg += "Fix violations. See ~/.margin/writing-rules.md for rules."

            print(json.dumps({
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": "ask",
                    "permissionDecisionReason": msg
                }
            }))

    except Exception as e:
        # Fail-open: never block writes due to hook errors
        print(f"Writing guard encountered an error (fail-open): {e}", file=sys.stderr)

    sys.exit(0)

if __name__ == "__main__":
    main()
`, string(killWordsJSON), string(slopPatternsJSON), string(headingPatternsJSON), string(autoCorrectionsJSON))
}

// ExportProfile writes the unified writing profile and agent-specific artifacts.
//
// target="" (default): writes ~/.margin/writing-rules.md and
// ~/.claude/hooks/writing_guard.py. Also updates ~/.codex/AGENTS.md if
// ~/.codex exists (opt-in by directory presence). Errors updating Codex are
// non-fatal — they don't break the Claude pipeline if Codex isn't set up.
//
// target="codex": writes ~/.margin/writing-rules.md and ~/.codex/AGENTS.md.
// Skips writing_guard.py — Codex uses prompt-level instructions instead of a hook.
func ExportProfile(dbPath string, target string) error {
	d, err := db.OpenRead(dbPath)
	if err != nil {
		return err
	}
	defer d.Close()

	rules, err := db.GetWritingRules(d, nil)
	if err != nil {
		return err
	}

	corrections, err := db.GetAllCorrectionsForProfile(d)
	if err != nil {
		return err
	}

	home, _ := os.UserHomeDir()

	// Always write writing-rules.md — the universal, LLM-agnostic artifact.
	profileMD := FormatProfileMarkdown(rules, corrections)
	rulesPath := filepath.Join(home, ".margin", "writing-rules.md")
	if err := os.WriteFile(rulesPath, []byte(profileMD), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", rulesPath, err)
	}

	if target == "codex" {
		// Codex target: update AGENTS.md instead of writing the Claude hook.
		return ExportCodex(dbPath)
	}

	// Default (Claude) target: write writing_guard.py.
	guardPy := GenerateWritingGuardPy(rules)
	hooksDir := filepath.Join(home, ".claude", "hooks")
	os.MkdirAll(hooksDir, 0755)
	guardPath := filepath.Join(hooksDir, "writing_guard.py")
	if err := os.WriteFile(guardPath, []byte(guardPy), 0755); err != nil {
		return fmt.Errorf("failed to write %s: %w", guardPath, err)
	}

	// Also update ~/.codex/AGENTS.md if Codex CLI is installed (opt-in by directory presence).
	// Errors are non-fatal — don't break the Claude pipeline if Codex isn't set up.
	if _, statErr := os.Stat(CodexDir()); statErr == nil {
		managed := FormatCodexAgentsMD(rules, corrections)
		agentsPath := CodexAgentsMDPath()
		existing, readErr := os.ReadFile(agentsPath)
		var content string
		if readErr == nil {
			content = mergeCodexAgentsMD(string(existing), managed)
		} else {
			content = managed
		}
		_ = os.WriteFile(agentsPath, []byte(content), 0644)
	}

	return nil
}
